// <auto-generated />
using System;
using APIDEMO_.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIDEMO_.Migrations
{
    [DbContext(typeof(ApiAppContext))]
    partial class ApiAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIDEMO_.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("23a04364-9f8b-4354-95fc-18169a4b3eda"),
                            Active = true,
                            DateCreated = new DateTime(2024, 10, 16, 9, 54, 42, 721, DateTimeKind.Local).AddTicks(3436),
                            LastName = "Fernandez",
                            Name = "Luis"
                        },
                        new
                        {
                            UserId = new Guid("56b61cc2-f6ae-41ce-b228-f497f4a406a4"),
                            Active = true,
                            DateCreated = new DateTime(2024, 10, 16, 9, 54, 42, 721, DateTimeKind.Local).AddTicks(3455),
                            LastName = "Polio",
                            Name = "Gustavo"
                        });
                });

            modelBuilder.Entity("APIDEMO_.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserRoleId = new Guid("57b4a0c1-4937-42d3-80d5-93ca31df0725"),
                            Active = true,
                            Role = "Admin",
                            UserId = new Guid("23a04364-9f8b-4354-95fc-18169a4b3eda")
                        },
                        new
                        {
                            UserRoleId = new Guid("0d348d01-85da-404b-aaf1-219a892b4439"),
                            Active = true,
                            Role = "User",
                            UserId = new Guid("23a04364-9f8b-4354-95fc-18169a4b3eda")
                        },
                        new
                        {
                            UserRoleId = new Guid("56e1fcf6-a832-49b8-accb-c138b307533e"),
                            Active = true,
                            Role = "Support",
                            UserId = new Guid("23a04364-9f8b-4354-95fc-18169a4b3eda")
                        },
                        new
                        {
                            UserRoleId = new Guid("6868a947-cd59-4714-b382-d44bff29e62e"),
                            Active = true,
                            Role = "Admin",
                            UserId = new Guid("56b61cc2-f6ae-41ce-b228-f497f4a406a4")
                        });
                });

            modelBuilder.Entity("APIDEMO_.Models.UserRole", b =>
                {
                    b.HasOne("APIDEMO_.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIDEMO_.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
